### ISSUE TITLE
Allow the repo to be used as Template repository

### ISSUE THREAD

**Issue by choukha** [Statoil/data-science-template#24]
I think, we should allow people to use the repo as a Template directly by making this as  Template repository, as shown here https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

The benefits of this way are described here https://docs.github.com/en/free-pro-team@latest/github/creating-cloning-and-archiving-repositories/creating-a-repository-from-a-template#about-repository-templates

**Comment by mahewitt** [comment]
Hi @choukha Are you thinking the repository as is, or a generated version? It wouldn't make much sense to add the template as-is as it is designed to run through cookie cutter to add project specific naming and otherwise. Having a generated version and setting as a template repository you would also lose these benefits from what I can see?

**Comment by choukha** [comment]
That's correct @mahewitt , the only customization Github allow is the repository name when using a template to create a new repo, You're right that all the cookie cutter advantages will be lost. I was trying to find out a way for a command line free process to set this up, but appears like template isn't the best way as of now & generated version will have the hardcoded cookie cutter config values.

**Comment by mahewitt** [comment]
Then I will close this
